### ISSUE TITLE
请问这个gan是干什么的呢？

### ISSUE THREAD

**Issue by AIHHU** [Perfect-You/SDACD#1]
大佬好，有点没看懂这个gan，请问是宁用来生成测试集的吗？

**Comment by Perfect-You** [comment]
您好，GAN网络主要是用来完成图像自适应，生成风格相同的前后时相图片输入到后面的特征提取网络中，从图像外观角度缩小双时相图像之间的领域差异。

**Comment by AIHHU** [comment]
您好，那请问这个训练这个gan需要单独训练吗？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年4月26日 11:28
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Perfect-You/SDACD] 请问这个gan是干什么的呢？ (Issue #1)


您好，GAN网络主要是用来完成图像自适应，生成风格相同的前后时相图片输入到后面的特征提取网络中，从图像外观角度缩小双时相图像之间的领域差异。

―

**Comment by Perfect-You** [comment]
GAN网络不需要单独训练，整个网络是端到端进行训练的。

**Comment by AIHHU** [comment]
大佬，抱歉我没仔细看论文鸭，就是这个训练标签就是变化的二值图像是吗？这里没用多任务联合训练吧

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年4月26日 11:40
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Perfect-You/SDACD] 请问这个gan是干什么的呢？ (Issue #1)


GAN网络不需要单独训练，整个网络是端到端进行训练的。

―

**Comment by Perfect-You** [comment]
是的，训练的标签是二值图像，0表示非变化，1表示变化。领域自适应和变化检测一起训练，也可以当作是多任务联合训练。
