### ISSUE TITLE
single-card training&eval.py

### ISSUE THREAD

**Issue by neil-jinsh-public** [Perfect-You/SDACD#10]
Hello, I have been following the development of this model.

There are a few questions (including those from previous scholars) that I would like to hear from you.

1. Do you currently have the code for single-card training?

2. In eval.py (line 80) , the model () function can only return four variables, but is decompressed by five variable names, so there is not enough value to decompress (expect 5, get 4) . How can this be explained or modified?

Finally, thank you and all the authors for sharing.

**Comment by Perfect-You** [comment]
1. We currently have no plans for a single-card training version.
2. We have uploaded the code and you can download the new version of eval.py for experiment.
