### ISSUE TITLE
关于性能

### ISSUE THREAD

**Issue by AIHHU** [Perfect-You/SDACD#2]
请问您觉得和bit-cd相比，宁这个怎么样？

**Comment by Perfect-You** [comment]
您好，bit-cd是论文《Remote Sensing Image Change Detection with Transformers》提出的方法吗，这篇论文中使用的数据集和我们论文中的有些差异（WHU的训练集和测试集划分不同），我们也没有对bit-cd做对比实验，所以目前还没有方法比较的具体结论。
