### ISSUE TITLE
The label of the CDD dataset is not binary map.

### ISSUE THREAD

**Issue by yiyi-today** [Perfect-You/SDACD#7]
Thank you for your generous sharing！

I downloaded the CDD dataset mentioned in your paper, but found that the label of the CDD dataset was not binary map, as Issue in label dataset of 2018. Lebedev M A, Vizilter Y V, Vygolov O V, et al. Change detection in remote sensing images using conditional adversarial networks said.

How did you deal with this situation ?

thanks

**Comment by Perfect-You** [comment]
We didn't encounter similar problem in the experiments, and we hope you can describe your problem more clear.
