### ISSUE TITLE
get weights

### ISSUE THREAD

**Issue by ArmanFahradyan** [Perfect-You/SDACD#9]
Hello, 

Could you please tell me how can get an access to the trained weights mentioned in the readme. There is a way based on Chinese account but I don't have one. 
Please inform me how can I get the pretrained weights without baidu account.

**Comment by Perfect-You** [comment]
We have uploaded the pretrained model to google drive, the link is https://drive.google.com/drive/folders/13bp7FbOBUtQi_zkhE6GpetRgjms9TuF9?usp=sharing, you can download it.
